### ISSUE TITLE
Hede-io displays markdown used after publishing a comment

### ISSUE THREAD

**Issue by realrufans** [Hede-io/hede.io#1]
#### Expected behavior
The markdown used while commenting on a post wasn't expected to display  after publishing the comment.

#### Actual behavior
It happens that the markdown displayed via Hede.io
![IMG-20180629-WA0000.jpg](https://cdn.steemitimages.com/DQmQScEhxCCj9KGWAAumcrgbeKrSFjbu5rNTsLxxuuAY9iw/IMG-20180629-WA0000.jpg)

But the markdown isn't displaying via Steemit.
![Screenshot_20180629-214533.png](https://cdn.steemitimages.com/DQmcteTcN4A223fbkbbcwhLtBYeLywmfeWU1k1a42R5Di9m/Screenshot_20180629-214533.png)

<Hr>

 
*I tried replying to a comment with a markdown via Hede*
![Screenshot_20180629-232630.png](https://cdn.steemitimages.com/DQmXGyZUBjUMfuBXd8Zd5ZuvyYVfAk8aNxAeRaGLieE46os/Screenshot_20180629-232630.png)

*It resulted to this , after publishing it*
![Screenshot_20180629-232652.png](https://cdn.steemitimages.com/DQmQBaeEFVPaPbFygek9eaM6DuUJacpDyr1VGDgeqR6MHX9/Screenshot_20180629-232652.png)

*But it displayed properly via Steemit*
![Screenshot_20180629-232705_1530311288182.png](https://cdn.steemitimages.com/DQmUwuhfMqvDSy8zRwDDBYdh3ELobxBgpKL4VyKJak3qUfe/Screenshot_20180629-232705_1530311288182.png)

#### How to reproduce
* Go to https://hede.io/hede-io/@ercu/hede-io
* Locate the comment made by sneaky-ninja

Or go to https://hede.io/hede-io/@readarthurss/amala#@readarthurss/re-ercu-re-readarthurss-amala-20180629t155735349z to view  the comment by readarthurss

* Browser/App version & Operating system
![Screenshot_20180629-203657_1530301209243.png](https://cdn.steemitimages.com/DQmfF15HHoyiAGnb5tJUwJRz7jtwz2rNxh4P6dHggEA3FUx/Screenshot_20180629-203657_1530301209243.png)

#### Recording Of The Bug
https://youtu.be/I1doxyx26jQ

**Comment by tobias-g1** [comment]
I was able to replicate this issue on the following environment:

- Browser: Google Chrome (Version 65.0.3325.162 (Official Build) (64-bit))
- Device: MacBook Pro (Retina, 15-inch, Late 2013)
- Operating system: MacOS HighSierra Version 10.13

There seem to be two issues to resolve within this issue:

- [ ] HTML should be rendered within a post
- [ ] Support multi-line markdown comments, currently they're being converted in URL links.

**Comment by ercu** [comment]
Thanks for the issue. We don't support Html codes and will not support in the future. Reason is, creates UI hierarchy ambiguity with the topic title and makes people use them more blog-post like. So to solve this we will strip html tags showing on the comments and posts.

For the markdown example, HEDE converts that markdown into Hidden Reference urls to other topics. We only support 1 quote one instead of 3 one. So we can just strip those too.
