### ISSUE TITLE
Cannot be change language, when doing reload, the language will return to english

### ISSUE THREAD

**Issue by shaphir** [Hede-io/hede.io#10]
#### Actual behavior
I tried to change the language to arabic language, but the language will return to English when I try reload
![20180630_215751](https://user-images.githubusercontent.com/38022258/42126351-54776b24-7cb1-11e8-873e-7a23c08068b1.gif)

* Browser: Google Chore fast & secure version 67.0.3396.87
* Operating system: Android 6.0.1

**Comment by ercu** [comment]
Thanks for the bug-hunt. The default language option is forced to be English for now. Any code contributor should store the selected language to close this issue.
