### ISSUE TITLE
Can not login in hede.io via Firefox

### ISSUE THREAD

**Issue by ahyar92** [Hede-io/hede.io#19]
### Expected behavior
Supposedly, I can login through steemconnect on via laptop without any problems.

### Actual behavior
When I try to open the site hede.io and want to login through steemconnect, suddenly the login process does not work. And I have logged back, but the error still occurs.

### How to reproduce
1. Click the following link https://hede.io/
2. Next, click the login feature
3. Login via steemconnect and the contents of the username and password of the steemit account. *Then you will find the error as I experienced*.

----
### Environment
<table>
<thead>
<tr></tr><tr><th>Operating system</th><th>Browser version</th>
</tr></thead>
<tbody>
<tr></tr><tr><td>Windows 7</td><td>Mozilla Firefox 61.0 (32-bit)</td>
</tr></tbody>
</table>

### Recording Of The Bug
https://www.youtube.com/watch?v=K1KZhatrwXM&feature=youtu.be

**Comment by ercu** [comment]
Could you send any console errors from Inspect/Developer Tools, so I can analyse better? 

Today there was a steem problem that prevented Steem RPC functioning maybe it is related to this. Also could you please try again now as RPC api seems working?

**Comment by sourovafrin** [comment]
I am sure that, he tried to login when blockchain was freeze

**Comment by ercu** [comment]
Ok I have experienced same problem on Firefox. After login, current page does not show the logged in state, however when you open a new tab it shows you as logged in. Thanks for the issue!

**Comment by ercu** [comment]
Should be fixed with #24 , Re-open if you still can not login via Firefox.
