### ISSUE TITLE
Hede.io doesn't display user correct voting power

### ISSUE THREAD

**Issue by jubreal** [Hede-io/hede.io#3]
#### Expected behavior       
The user info and profile displayed while using the hede.io platform should be correct and convey the true user status.
 
 
#### Actual behavior       
The voting power of the user displayed while using hede.io is not correct and misinform users.
 
 
#### How to reproduce
1.     Visit ``` https://hede.io   ``` and log in with your steemit details via steemconnect.   
2.     Go to user profile page by clicking on the user display picture.   
3.     Observe the voting power value   
4.     Visit user ``` https://steemd.com   ``` of the same user. Observe the value of the voting power.       
It will be   observed that the there is a discrepancy in the voting power value, hence, the   bug
 
* Browser/App version:  Chrome Browser version 67.0.3396.87
* Operating system: Android 6.0
 
#### Recording Of The Bug       
https://youtu.be/dEknsjiw9es

**Comment by sachincool** [comment]
For the devs,  https://github.com/busyorg/busy/issues/957 There was a similar problem with busy which is fixed now.

**Comment by ercu** [comment]
Thank you. 
We we not using the VP calculating function which adds regenerated VP to previous VP.
Fixed with commit b64e80232b269bade2f604333026b687e875a820.

**Comment by ercu** [comment]
#20
