### ISSUE TITLE
Wrong post rewards value 

### ISSUE THREAD

**Issue by onos1** [Hede-io/hede.io#30]
I discovered the post rewards value for hede.io is different from what is on steemit. And Steemit.com is correct. 

- for Steemit.com 
[![Screenshot_20180718-153634.png](https://s22.postimg.cc/6xxgesacx/Screenshot_20180718-153634.png)](https://postimg.cc/image/vefm99b3h/)

- for hede.io 
[![Screenshot_20180718-153650.png](https://s22.postimg.cc/f4pg5v801/Screenshot_20180718-153650.png)](https://postimg.cc/image/jdu681b99/)

Even after refreshing countless times, the vote amount and numbers seems to be incorrect.

**Comment by ercu** [comment]
We don't update rewards periodically, thus don't fetch the upvotes given via other interfaces. Although this is an intended behavior, we might be change in the future.

**Comment by onos1** [comment]
I think it's best the current way then
