### ISSUE TITLE
Hede shows an error when page is reloaded on setting page and also unable to surf the page by directly going to setting link

### ISSUE THREAD

**Issue by sourovafrin** [Hede-io/hede.io#4]
#### Expected behavior

I expected that i will be able to reload any page of hede and will be able to directly surf a page by clicking on it's link

#### Actual behavior

Whenever i reload on hede's setting page, it shows an error- `undefined is not a function`
I was also unable to visit the page by directly going to setting link

#### How to reproduce

- First of all log in with your posting key on hede.io

- Now on upper right side, beside the profile picture, you will see a 3dot menu, click on it.

- Now click on setting to visit setting page.

- After landing on setting page, reload the page, It will show `undefined is not a function` error

- You can directly go to this link- https://hede.io/settings . Same stuff will happen.

* Browser version: Chrome Version 67.0.3396.87 (Official Build) (64-bit)

* Operating system: Windows 8.1

#### Recording Of The Bug
![rec-2018-06-30-13-19-41](https://user-images.githubusercontent.com/38147368/42122820-7ce09c0e-7c69-11e8-8cba-d27458b70cb6.gif)

**Comment by ercu** [comment]
I think Server render does not support settings page yet. We will have to add that to server render routes fix it.

**Comment by ercu** [comment]
Should be fixed with #21
