### ISSUE TITLE
Cookies text overlaps with the hot topics sidebar and is hard to read

### ISSUE THREAD

**Issue by espoem** [Hede-io/hede.io#8]
### Actual behaviour

When a user visits the page, the bar with cookies is shown. The text on the left in the bar overlaps, therefore it is not readable.

![image](https://user-images.githubusercontent.com/16621517/42123851-33696598-7c59-11e8-94a2-2a37de56b4b9.png)

- browser: Chrome 67
- OS: Windows 10

**Comment by sourovafrin** [comment]
I observed this issue. one more issue similar to this is #5

**Comment by espoem** [comment]
Yep, it is the same issue. I overlooked it.

**Comment by ercu** [comment]
For me, #5 is similar but not the same issues. The topic list is a different UI element and the problem here exists on both Mobile and Desktop, unlike #5. Changing z-index of .CookiePolicyBanner css class to 10 will fix it. Me or any contributor using PR can do that.

**Comment by ercu** [comment]
Should be fixed with #22
