### ISSUE TITLE
An error occurs when switching to the desktop site on the settings

### ISSUE THREAD

**Issue by shaphir** [Hede-io/hede.io#9]
#### Actual behavior
After I'm on the settings, I try to change the look of the phone from mobile version to desktop site, the site suddenly displays an error
![20180630_214056](https://user-images.githubusercontent.com/38022258/42126213-a32dab14-7cae-11e8-8315-695e807ee23f.gif)

* Browser: Google Chore fast & secure version 67.0.3396.87
* Operating system: Android 6.0.1

**Comment by sourovafrin** [comment]
This report is already done by me. check #4 . When you change mode the page reloads and it became similar to my posted one

**Comment by shaphir** [comment]
Oh sorry, i not see it
